version: "3.7"
services:
  sogos:
    image: sogos
    build:
      context: .
    ports:
      - 8888:8888
    depends_on:
      - mongo
      - keycloak
    environment:
      - sogos.hmac.key=FamRavioli!
      - sogos.client.id=sogos-app
      - sogos.openid.provider=http://keycloak:8080/auth/realms/master
      - sogos.openid.provider.ui=http://localhost:8180/auth/realms/master
      - sogos.provider=KEYCLOAK
      - sogos.client.id.ui=sogos-app
      - sogos.mongo.connection=mongodb://mongo:27017/local
  mongo:
      image: mongo
      volumes:
        - mongo-volume:/data/db
      ports:
        - "27017:27017"
  keycloak:
    image: jboss/keycloak
    ports:
      - "8180:8080"
    depends_on:
      - postgres
    environment:
      - KEYCLOAK_USER=alex
      - KEYCLOAK_PASSWORD=simons
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_USER=keycloak
      - DB_PASSWORD=password
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  localstack-s3:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3:5002
      - DEFAULT_REGION=eu-west-2
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "5002:5002"
      - "9999:8080"
    volumes:
      - localstack-data:/tmp/localstack

volumes:
  localstack-data:
    name: localstack-data
  postgres-volume:
  mongo-volume:
