const val CLIENT_ID = "sogos.client.id"
const val OPENID_PROVIDER = "sogos.openid.provider"
const val PROVIDER = "sogos.provider"
const val CLIENT_ID_UI = "sogos.client.id.ui"
const val HMAC_KEY = "sogos.hmac.key"
const val CLIENT_SECRET = "sogos.client.secret"
const val CONNECTION_STRING = "sogos.mongo.connection"
