const val CLIENT_SECRET = "sogos.client.secret"

const val CONNECTION_STRING = "sogos.mongo.connection"
const val HMAC_KEY = "sogos.hmac.key"
const val CLIENT_ID = "sogos.client.id"
const val CLIENT_ID_UI = "sogos.client.id.ui"
const val OPENID_PROVIDER = "sogos.openid.provider"
const val OPENID_PROVIDER_UI = "sogos.openid.provider.ui"
const val PROVIDER = "sogos.provider"
const val AUTH_URL = "sogos.auth.url"
const val TOKEN_URL = "sogos.token.url"
const val USER_INFO_URL = "sogos.user.info.url"
const val LOGOUT_URL = "sogos.logout.url"
const val EMAIL_EXTRACTOR = "sogos.email.extractor"

const val PORT_NUMBER = "sogos.port"
