plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-aws-alias

service: sogos-api

provider:
  name: aws
  runtime: nodejs12.x

custom:
  serverless-offline:
    port: 8888
    host: 0.0.0.0


functions:
  sogos:
    handler: src/index.handler
    events:
      - http:
          path: / # this matches the base path
          method: ANY
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY


